export const USAGE = [
  "Usage: keel [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--allow-bash] [--bash-policy <ask|deny|trusted>] [--max-cost <usd>] [--report <file>] [--transcript <file>] [--skill <[scope:]name>]... [--no-skills] [--no-memory] <message>",
  "       keel [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--allow-bash] [--bash-policy <ask|deny|trusted>] [--max-cost <usd>] [--report <file>] [--skill <name>] [--no-skills] [--ephemeral | --session <id> | --resume [<id>] | --resume --pick | --resume <id> --fork-points | --resume <id> --fork <new-id> [--fork-before-message <id>]]",
  "       keel goal --objective <text> (--verify <command> [--timeout 30s] | --done-when <criterion>) [--turns N] [--tokens N] [--time 30m] [--session <id>] [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--bash-policy <ask|deny|trusted>] [--max-cost <usd>] [--report <file>] [--skill <name>] [--no-skills] [--no-memory]",
  "       keel goal resume (<session-id> | --last) [--turns N] [--tokens N] [--time 30m] [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--bash-policy <ask|deny|trusted>] [--max-cost <usd>] [--report <file>] [--skill <name>] [--no-skills] [--no-memory]",
  "       keel --doctor [--offline] [--provider <fake|deepseek|kimi|qwen>] [--model <id>]",
  "       keel auth login <deepseek|kimi|qwen> --with-api-key",
  "       keel auth status",
  "       keel auth logout <deepseek|kimi|qwen>",
  "       keel setup <deepseek|kimi|qwen> --with-api-key [--model <id>] [--base-url <url>] [--offline]",
  "       keel config set-provider <fake|deepseek|kimi|qwen> [--model <id>] [--base-url <url>]",
  "       keel config show",
  "       keel sessions",
  "       keel sessions show <id> [--limit <n> | --all]",
  "       keel sessions fork <source-id> <target-id> [--before-message <id>]",
  "       keel approvals",
  "       keel approvals revoke <index>",
  "       keel approvals clear",
  "       keel memory add <durable-fact>",
  "       keel memory list",
  "       keel memory forget <id>",
  "       keel memory clear [--yes]",
  "       keel artifacts show <ref>",
  "       keel skills",
  "       keel skills doctor",
  "       keel skills <enable|disable> <[scope:]name|--all>",
  "       keel eval [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--suite <dir>] [--task <id>] [--trials <n>] [--out <file>] [--transcript-dir <dir>] [--check]",
  "       keel eval compare --base <old.jsonl> --head <new.jsonl>",
  "       keel /undo [--list | --to <index>]",
  "       keel --help | -h",
  "",
  "--allow-bash enables trusted shell commands. Shell commands run with the current OS user's permissions and may read or modify gitignored files.",
  "Project memory is explicit and project-scoped. Save only durable rules, preferences, decisions, and observable facts; use --no-memory for a run with no memory discovery or injection.",
  "Project memory requires a reliable local filesystem. Cloud-synced stores and concurrent multi-host writers are unsupported.",
  "--bash-policy controls shell command approval: ask requires a real TTY approval prompt, deny disables bash, trusted runs commands without per-command approval. Approved or trusted command output may be sent to the provider unredacted. Do not combine it with --allow-bash; use --bash-policy trusted instead.",
  "--max-cost sets a best-effort session cost budget. Keel conservatively rejects requests that cannot fit, bounds provider output when possible, and reports any remaining post-response overshoot; it is not a guaranteed provider billing ceiling.",
  "--report writes a machine-readable JSON run report (human interventions, turns, stop reason, token usage, cost) to the given file; ordinary one-shot and interactive graceful stops still exit normally, while headless Goal runs also expose stable outcome exit codes and goalOutcome metadata.",
  "--transcript writes a best-effort redacted provider-visible one-shot transcript as schema-versioned JSONL. Live provider requests are not redacted.",
  "--skill is repeatable and activates workflow guidance by a unique name or qualified repo:, user:, system:, or extra: identity. Same-scope collisions add a root-id segment. $name, $scope:name, and $scope:root-id:name provide the same explicit one-shot syntax; /skill does so interactively.",
  "--no-skills disables workflow Skill discovery, catalog exposure, tools, explicit activation, and restored active snapshots for the current run; it cannot be combined with --skill.",
  "Skills are discovered from every repository .agents/skills root, ~/.agents/skills, KEEL_HOME/skills/.system, KEEL_SYSTEM_SKILL_ROOTS, and KEEL_EXTRA_SKILL_ROOTS. Environment root lists use the platform path delimiter.",
  "skills doctor audits every discovered Skill package without executing it, reports deterministic blockers and warnings, and exits non-zero when any package is blocked.",
  "skills disable --all persists a global Skill shutdown; skills disable <name> removes one stable package from runtime catalogs, tools, explicit activation, and restored snapshots. skills enable reverses those controls. --no-skills remains the absolute per-run override.",
  "goal runs one command-verified or assertion-evaluated saved Goal without an interactive terminal; --verify and --done-when are mutually exclusive. Assertion completion uses the same fresh external evaluator hard gate as interactive Goals and needs no verifier authorization. goal resume continues the same durable Goal by id or selects the latest resumable Goal with --last. Resume --turns/--tokens/--time replace only the supplied absolute durable budget limits before continuation. Both exit 0 when completed, 3 when blocked, and 4 when limited; other failures use the normal CLI exit codes. Command verification requires trusted Bash or a matching saved project approval on every launch or resume.",
  "Interactive sessions persist provider context by default with best-effort at-rest redaction; use --ephemeral to skip the session ledger. Live provider requests may still include raw user and tool content.",
  "--session names a new interactive session; --resume continues the latest saved interactive session for the current workspace, --resume --pick lets a real TTY choose one, or --resume <id> resumes a specific session.",
  "--limit controls how many recent restored messages sessions show prints; --all prints the full restored timeline.",
  "--fork-points lists restored user message ids for sessions fork --before-message; it requires --resume.",
  "--fork-before-message cuts a fork before the restored message id; it requires --resume and --fork.",
  "--before-message cuts a sessions fork before the restored message id.",
  "approvals lists and removes project-scoped bash approvals stored under KEEL_HOME for the current project.",
  "Tool output artifacts are raw, unredacted tool output managed under KEEL_HOME and retained for 30 days by default or until manual removal; use keel artifacts show <ref> to inspect full saved output.",
  "auth login reads an API key from stdin and stores it in KEEL_HOME auth.json with redacted status output.",
  "setup reads an API key from stdin, stores provider auth/config, then runs doctor; use --offline to skip the online auth probe.",
  "config set-provider stores non-secret provider defaults in KEEL_HOME config.json; CLI flags and environment variables still override it.",
  "--transcript-dir writes one best-effort redacted provider-visible transcript JSONL file per eval trial.",
  "--provider and --model override provider env for the current run.",
  "Provider env: KEEL_PROVIDER=deepseek|kimi|qwen, DEEPSEEK_API_KEY, KIMI_API_KEY, DASHSCOPE_API_KEY or QWEN_API_KEY, optional *_BASE_URL, DEEPSEEK_MODEL, KIMI_MODEL, QWEN_MODEL, and KEEL_CONTEXT_WINDOW_TOKENS.",
  "Context compaction uses model registry context windows; set KEEL_CONTEXT_WINDOW_TOKENS to override the selected model window.",
  "Qwen default endpoint is https://dashscope-intl.aliyuncs.com/compatible-mode/v1; set QWEN_BASE_URL if your key belongs to China region or a workspace-scoped DashScope endpoint.",
].join("\n");
