export const USAGE = [
  "Usage: keel [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--allow-bash] [--bash-policy <ask|deny|trusted>] [--agent-policy <off|explicit|auto>] [--max-cost <usd>] [--report <file>] [--transcript <file>] [--skill <[scope:]name>]... [--no-skills] [--no-memory] <message>",
  "       keel [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--allow-bash] [--bash-policy <ask|deny|trusted>] [--agent-policy <off|explicit|auto>] [--max-cost <usd>] [--report <file>] [--skill <name>] [--no-skills] [--ephemeral | --session <id> | --resume [<id>] | --resume --pick | --resume <id> --fork-points | --resume <id> --fork <new-id> [--fork-before-message <id>]]",
  "       keel goal --objective <text> (--verify <command> [--timeout 30s] | --done-when <criterion>) [--turns N] [--tokens N] [--time 30m] [--session <id>] [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--bash-policy <ask|deny|trusted>] [--max-cost <usd>] [--report <file>] [--skill <name>] [--no-skills] [--no-memory]",
  "       keel goal resume (<session-id> | --last) [--turns N] [--tokens N] [--time 30m] [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--bash-policy <ask|deny|trusted>] [--max-cost <usd>] [--report <file>] [--skill <name>] [--no-skills] [--no-memory]",
  "       keel --doctor [--offline] [--provider <fake|deepseek|kimi|qwen>] [--model <id>]",
  "       keel auth login <deepseek|kimi|qwen> --with-api-key",
  "       keel auth status",
  "       keel auth logout <deepseek|kimi|qwen>",
  "       keel setup <deepseek|kimi|qwen> --with-api-key [--model <id>] [--base-url <url>] [--offline]",
  "       keel config set-provider <fake|deepseek|kimi|qwen> [--model <id>] [--base-url <url>]",
  "       keel config show",
  "       keel mcp add <url> [--name <id>] [--allow-private-network] [--allow-tool <name>]... [--deny-tool <name>]...",
  "       keel mcp list",
  "       keel mcp status [server]",
  "       keel mcp doctor [server]",
  "       keel mcp login <server> [--client-id <id> [--with-client-secret]]",
  "       keel mcp logout <server>",
  "       keel mcp enable <server>",
  "       keel mcp disable <server>",
  "       keel mcp remove <server>",
  "       keel mcp approvals list",
  "       keel mcp approvals revoke <index>",
  "       keel mcp approvals clear",
  "       keel sessions",
  "       keel sessions show <id> [--limit <n> | --all]",
  "       keel sessions fork <source-id> <target-id> [--before-message <id>]",
  "       keel sessions repair <id> --truncate-incomplete-tail",
  "       keel approvals",
  "       keel approvals revoke <index>",
  "       keel approvals clear",
  "       keel memory add <durable-fact> [--review-after <timestamp>] [--expires-at <timestamp>]",
  "       keel memory list [--all]",
  "       keel memory show <id>",
  "       keel memory update <id> <replacement> [--review-after <timestamp>] [--expires-at <timestamp>]",
  "       keel memory review [--due]",
  "       keel memory verify <id>",
  "       keel memory forget <id>",
  "       keel memory purge <id>",
  "       keel memory clear [--purge] [--yes]",
  "       keel memory candidates extract <completed-root-session-id> --max-cost <usd> [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--retry]",
  "       keel memory candidates list",
  "       keel memory candidates show <candidate-id>",
  "       keel memory candidates edit <candidate-id> <replacement>",
  "       keel memory candidates approve <candidate-id> [--keep | --supersede <memory-id>]",
  "       keel memory candidates reject <candidate-id>",
  "       keel memory candidates purge <candidate-id> [--purge-memory <memory-id>]",
  "       keel memory candidates clear [--purge] [--purge-memories] [--yes]",
  "       keel artifacts show <ref>",
  "       keel skills",
  "       keel skills doctor",
  "       keel skills <enable|disable> <[scope:]name|--all>",
  "       keel eval [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--suite <dir>] [--task <id>] [--trials <n>] [--out <file>] [--transcript-dir <dir>] [--check]",
  "       keel eval compare --base <old.jsonl> --head <new.jsonl>",
  "       keel /undo [--list | --to <index>]",
  "       keel --help | -h",
  "",
  "--allow-bash enables trusted shell commands. Shell commands run with the current OS user's permissions and may read or modify gitignored files.",
  "Project memory is explicit and project-scoped. Save durable facts with memory commands or direct unambiguous current-user remember/forget requests; use --no-memory for a run with no memory discovery, injection, or mutation tools.",
  "Memory-candidate extraction is off by default. The explicit candidates extract command uses bounded current-user evidence from one completed persisted root session, creates inactive 30-day candidates, reports provider usage/cost, and requires review plus approval before active memory changes.",
  "Project memory requires a reliable local filesystem. Cloud-synced stores and concurrent multi-host writers are unsupported.",
  "--bash-policy controls shell command approval: ask requires a real TTY approval prompt, deny disables bash, trusted runs commands without per-command approval. Approved or trusted command output may be sent to the provider unredacted. Do not combine it with --allow-bash; use --bash-policy trusted instead.",
  "--max-cost sets a best-effort session cost budget. Keel conservatively rejects requests that cannot fit, bounds provider output when possible, and reports any remaining post-response overshoot; it is not a guaranteed provider billing ceiling.",
  "--agent-policy controls governed children. off is the default; explicit permits delegation only after the current user asks for a subagent, while auto lets the model select eligible independent read-only work. explicit and auto require --max-cost. One-shot and ephemeral runs admit foreground children only; saved interactive sessions also admit attached background read-only children with live list, wait, and cancel controls. Under explicit policy, a foreground read-only child may delegate a foreground read-only subtask one level deeper; depth-two children cannot delegate, write, run Bash, or start background work. Only explicit policy exposes a writer: one foreground child may edit an isolated branch/worktree from a clean Git checkout, returns an inspectable patch and preserved path, and never edits or merges the user's checkout. Projects may define narrowing-only repo:<name> profiles in .agents/subagents.json. A pure read-only delegate round may run up to four children concurrently; one-shot runs and each live saved-session owner admit at most eight children across the tree. All levels share root budget, provider limits, cancellation, admission, and durable session history, and main remains the only final answerer.",
  "--report writes a machine-readable JSON run report (human interventions, turns, stop reason, token usage, cost) to the given file. Subagent model operations include delegation, child Run, profile, and effort attribution and roll into root usage/cost; saved-session /agents history remains the canonical lifecycle view. Terminal runtime failures best-effort add bounded redacted failure evidence without changing the non-zero exit, ordinary graceful stops still exit normally, and headless Goal runs also expose stable outcome exit codes and goalOutcome metadata.",
  "--transcript writes a best-effort redacted provider-visible one-shot transcript as schema-versioned JSONL. Live provider requests are not redacted.",
  "--skill is repeatable and activates workflow guidance by a unique name or qualified repo:, user:, system:, or extra: identity. Same-scope collisions add a root-id segment. $name, $scope:name, and $scope:root-id:name provide the same explicit one-shot syntax; /skill does so interactively.",
  "--no-skills disables workflow Skill discovery, catalog exposure, tools, explicit activation, and restored active snapshots for the current run; it cannot be combined with --skill.",
  "Skills are discovered from every repository .agents/skills root, ~/.agents/skills, KEEL_HOME/skills/.system, KEEL_SYSTEM_SKILL_ROOTS, and KEEL_EXTRA_SKILL_ROOTS. Environment root lists use the platform path delimiter.",
  "skills doctor audits every discovered Skill package without executing it, reports deterministic blockers and warnings, and exits non-zero when any package is blocked.",
  "skills disable --all persists a global Skill shutdown; skills disable <name> removes one stable package from runtime catalogs, tools, explicit activation, and restored snapshots. skills enable reverses those controls. --no-skills remains the absolute per-run override.",
  "goal runs one command-verified or assertion-evaluated saved Goal without an interactive terminal; --verify and --done-when are mutually exclusive. Assertion completion uses the same fresh external evaluator hard gate as interactive Goals and needs no verifier authorization. goal resume continues the same durable Goal by id or selects the latest resumable Goal with --last. Resume --turns/--tokens/--time replace only the supplied absolute durable budget limits before continuation. Both exit 0 when completed, 3 when blocked, and 4 when limited; other failures use the normal CLI exit codes. Command verification requires trusted Bash or a matching saved project approval on every launch or resume.",
  "Interactive sessions persist provider context by default with best-effort at-rest redaction; use --ephemeral to skip the session ledger. Live provider requests may still include raw user and tool content.",
  "--session names a new interactive session; --resume continues the latest saved interactive session for the current workspace, --resume --pick lets a real TTY choose one, or --resume <id> resumes a specific session.",
  "--limit controls how many recent restored messages sessions show prints; --all prints the full restored timeline.",
  "--fork-points lists restored user message ids for sessions fork --before-message; it requires --resume.",
  "--fork-before-message cuts a fork before the restored message id; it requires --resume and --fork.",
  "--before-message cuts a sessions fork before the restored message id.",
  "--truncate-incomplete-tail explicitly repairs only a crash-truncated final JSONL fragment after validating the retained session prefix and preserving the original ledger.",
  "approvals lists and removes project-scoped bash approvals stored under KEEL_HOME for the current project.",
  "Tool output artifacts are raw, unredacted tool output managed under KEEL_HOME and retained for 30 days by default or until manual removal; use keel artifacts show <ref> to inspect full saved output.",
  "auth login reads an API key from stdin and stores it in KEEL_HOME auth.json with redacted status output.",
  "mcp login --with-client-secret requires a bounded single-line secret piped on stdin; TTY entry is rejected to prevent terminal echo.",
  "mcp approvals lists and removes exact project-scoped MCP call approvals. A saved grant is bound to the server configuration, tool descriptor, authorization grant, and exact arguments; changed bindings fail closed.",
  "setup reads an API key from stdin, stores provider auth/config, then runs doctor; use --offline to skip the online auth probe.",
  "config set-provider stores non-secret provider defaults in KEEL_HOME config.json; CLI flags and environment variables still override it.",
  "--transcript-dir writes one best-effort redacted provider-visible transcript JSONL file per eval trial.",
  "--provider and --model override provider env for the current run.",
  "Provider env: KEEL_PROVIDER=deepseek|kimi|qwen, DEEPSEEK_API_KEY, KIMI_API_KEY, DASHSCOPE_API_KEY or QWEN_API_KEY, optional *_BASE_URL, DEEPSEEK_MODEL, KIMI_MODEL, QWEN_MODEL, and KEEL_CONTEXT_WINDOW_TOKENS.",
  "Context compaction uses model registry context windows; set KEEL_CONTEXT_WINDOW_TOKENS to override the selected model window.",
  "Qwen default endpoint is https://dashscope-intl.aliyuncs.com/compatible-mode/v1; set QWEN_BASE_URL if your key belongs to China region or a workspace-scoped DashScope endpoint.",
].join("\n");
