export const USAGE = [
  "Usage: keel [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--allow-bash] [--bash-policy <ask|deny|trusted>] [--max-cost <usd>] [--report <file>] [--transcript <file>] [--skill <name>] <message>",
  "       keel [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--allow-bash] [--bash-policy <ask|deny|trusted>] [--max-cost <usd>] [--report <file>] [--skill <name>] [--session <id> | --resume <id> [--fork-points | --fork <new-id> [--fork-before-message <id>]]]",
  "       keel --doctor [--offline] [--provider <fake|deepseek|kimi|qwen>] [--model <id>]",
  "       keel sessions",
  "       keel sessions show <id> [--limit <n> | --all]",
  "       keel sessions fork <source-id> <target-id> [--before-message <id>]",
  "       keel artifacts show <ref>",
  "       keel skills",
  "       keel eval [--provider <fake|deepseek|kimi|qwen>] [--model <id>] [--suite <dir>] [--task <id>] [--trials <n>] [--out <file>] [--transcript-dir <dir>] [--check]",
  "       keel eval compare --base <old.jsonl> --head <new.jsonl>",
  "       keel /undo [--list]",
  "       keel --help | -h",
  "",
  "--allow-bash enables trusted shell commands. Shell commands run with the current OS user's permissions and may read or modify gitignored files.",
  "--bash-policy controls shell command approval: ask requires a real TTY approval prompt, deny disables bash, trusted runs commands without per-command approval. Approved or trusted command output may be sent to the provider unredacted. Do not combine it with --allow-bash; use --bash-policy trusted instead.",
  "--report writes a machine-readable JSON run report (turns, stop reason, token usage, cost) to the given file; graceful non-completed stops still exit normally, so automation should read stopReason.",
  "--transcript writes a best-effort redacted provider-visible one-shot transcript as schema-versioned JSONL. Live provider requests are not redacted.",
  "--skill loads .agents/skills/<name>/SKILL.md as explicit workflow guidance for the current run.",
  "--session/--resume persist interactive provider context with best-effort at-rest redaction. Live provider requests may still include raw user and tool content.",
  "--limit controls how many recent restored messages sessions show prints; --all prints the full restored timeline.",
  "--fork-points lists restored user message ids for sessions fork --before-message; it requires --resume.",
  "--fork-before-message cuts a fork before the restored message id; it requires --resume and --fork.",
  "--before-message cuts a sessions fork before the restored message id.",
  "Tool output artifacts are managed under KEEL_HOME and retained until KEEL_HOME cleanup or manual removal; use keel artifacts show <ref> to inspect full saved output.",
  "--transcript-dir writes one best-effort redacted provider-visible transcript JSONL file per eval trial.",
  "--provider and --model override provider env for the current run.",
  "Provider env: KEEL_PROVIDER=deepseek|kimi|qwen, DEEPSEEK_API_KEY, KIMI_API_KEY, DASHSCOPE_API_KEY or QWEN_API_KEY, optional *_BASE_URL, DEEPSEEK_MODEL, KIMI_MODEL, QWEN_MODEL, and KEEL_CONTEXT_WINDOW_TOKENS.",
  "Context compaction uses model registry context windows; set KEEL_CONTEXT_WINDOW_TOKENS to override the selected model window.",
  "Qwen default endpoint is https://dashscope-intl.aliyuncs.com/compatible-mode/v1; set QWEN_BASE_URL if your key belongs to China region or a workspace-scoped DashScope endpoint.",
].join("\n");
